// Generates the TS enum and the C header from message-types.source.ts.
// Run: bun run protocol/codegen/generate.ts
// The codegen test regenerates in-memory and fails if the committed files drift.

import { MESSAGE_TYPES, AGENTBUS_VERSION, type MessageTypeDef } from "./message-types.source.ts";

const HEADER = "// GENERATED by protocol/codegen/generate.ts — DO NOT EDIT BY HAND.\n";

export function renderTs(types: readonly MessageTypeDef[], version: number): string {
  const entries = types.map((t) => `  ${t.name}: ${t.value},`).join("\n");
  const names = types.map((t) => `  [${t.value}, "${t.name}"],`).join("\n");
  return (
    HEADER +
    `\nexport const AGENTBUS_VERSION = ${version};\n\n` +
    `export const MSG = {\n${entries}\n} as const;\n\n` +
    `export type MsgName = keyof typeof MSG;\n` +
    `export type MsgCode = (typeof MSG)[MsgName];\n\n` +
    `const NAME_BY_CODE = new Map<number, string>([\n${names}\n]);\n\n` +
    `export function typeName(code: number): string | undefined {\n` +
    `  return NAME_BY_CODE.get(code);\n` +
    `}\n\n` +
    `export function isKnownType(code: number): boolean {\n` +
    `  return NAME_BY_CODE.has(code);\n` +
    `}\n`
  );
}

export function renderH(types: readonly MessageTypeDef[], version: number): string {
  const defines = types
    .map((t) => `#define AGENTBUS_MSG_${t.name} ${t.value}  /* ${t.dir}: ${t.doc} */`)
    .join("\n");
  return (
    "/* GENERATED by protocol/codegen/generate.ts — DO NOT EDIT BY HAND. */\n" +
    "#ifndef AGENTBUS_PROTOCOL_H\n#define AGENTBUS_PROTOCOL_H\n\n" +
    `#define AGENTBUS_VERSION ${version}\n\n` +
    "/* Wire frame: [u32 length BE][u8 type][u32 session_id BE][json payload]\n" +
    "   length counts everything after the length field. */\n\n" +
    defines +
    "\n\n#endif /* AGENTBUS_PROTOCOL_H */\n"
  );
}

const TS_PATH = new URL("../src/message-types.generated.ts", import.meta.url).pathname;
const H_PATH = new URL("../../client/source/protocol.h", import.meta.url).pathname;

export const generated = {
  ts: () => renderTs(MESSAGE_TYPES, AGENTBUS_VERSION),
  h: () => renderH(MESSAGE_TYPES, AGENTBUS_VERSION),
  tsPath: TS_PATH,
  hPath: H_PATH,
};

if (import.meta.main) {
  await Bun.write(TS_PATH, generated.ts());
  await Bun.write(H_PATH, generated.h());
  console.log("Wrote", TS_PATH, "and", H_PATH);
}
