// GENERATED by protocol/codegen/generate.ts — DO NOT EDIT BY HAND.

export const KEY_BYTES = 32; // XChaCha20-Poly1305 pre-shared key length
export const NONCE_BYTES = 24; // per-frame random nonce (192-bit, random-safe)
export const MAC_BYTES = 16; // Poly1305 authentication tag
export const MAX_RECORD_BYTES = 16380; // max sealed record (nonce|ct|mac); == client RXBUF minus the 4-byte outer length prefix. Both ends enforce this before buffering.
export const EPOCH_BYTES = 8; // per-connection anti-replay epoch, host-minted
export const SEQ_BYTES = 8; // per-direction monotonic counter (in AAD, not on wire)
export const DIR_DOWN = 0; // AAD direction byte: host -> device
export const DIR_UP = 1; // AAD direction byte: device -> host
export const CHALLENGE_BYTES = 8; // discovery probe random challenge
export const DISCOVERY_PROBE = 1; // discovery datagram TYPE: device -> host probe
export const DISCOVERY_REPLY = 2; // discovery datagram TYPE: host -> device reply
export const DEFAULT_TCP_PORT = 4791; // AgentBus TCP port (host listens)
export const DEFAULT_DISCOVERY_PORT = 41337; // UDP discovery port (host responder)

export const AAD_MSG_CONTEXT = "3dsendai-msg-v1"; // AAD domain tag for TCP frames
export const AAD_DSC_CONTEXT = "3dsendai-dsc-v1"; // AAD domain tag for discovery datagrams
export const DISCOVERY_MAGIC = "ag3n"; // discovery datagram magic prefix
