// GENERATED by protocol/codegen/generate.ts — DO NOT EDIT BY HAND.

export const AGENTBUS_VERSION = 1;

export const MSG = {
  HELLO: 1,
  SESSION_LIST: 2,
  SESSION_STATE: 3,
  OUTPUT_CHUNK: 4,
  APPROVAL_REQUEST: 5,
  TRANSCRIPT_PARTIAL: 6,
  MACROPAD_LAYOUT: 7,
  ERROR: 8,
  REPLAY_BEGIN: 9,
  REPLAY_END: 10,
  TERMINAL_DATA: 11,
  ALERT_SIGNAL: 12,
  ATTACH: 64,
  FOCUS_SESSION: 65,
  PROMPT_TEXT: 66,
  INPUT_EVENT: 67,
  APPROVAL_RESPONSE: 68,
  AUDIO_CHUNK: 69,
  MACRO_INTENT: 70,
  INTERRUPT: 71,
  KEYSTROKE: 72,
  CLIENT_SIZE: 73,
} as const;

export type MsgName = keyof typeof MSG;
export type MsgCode = (typeof MSG)[MsgName];

const NAME_BY_CODE = new Map<number, string>([
  [1, "HELLO"],
  [2, "SESSION_LIST"],
  [3, "SESSION_STATE"],
  [4, "OUTPUT_CHUNK"],
  [5, "APPROVAL_REQUEST"],
  [6, "TRANSCRIPT_PARTIAL"],
  [7, "MACROPAD_LAYOUT"],
  [8, "ERROR"],
  [9, "REPLAY_BEGIN"],
  [10, "REPLAY_END"],
  [11, "TERMINAL_DATA"],
  [12, "ALERT_SIGNAL"],
  [64, "ATTACH"],
  [65, "FOCUS_SESSION"],
  [66, "PROMPT_TEXT"],
  [67, "INPUT_EVENT"],
  [68, "APPROVAL_RESPONSE"],
  [69, "AUDIO_CHUNK"],
  [70, "MACRO_INTENT"],
  [71, "INTERRUPT"],
  [72, "KEYSTROKE"],
  [73, "CLIENT_SIZE"],
]);

export function typeName(code: number): string | undefined {
  return NAME_BY_CODE.get(code);
}

export function isKnownType(code: number): boolean {
  return NAME_BY_CODE.has(code);
}
