/* GENERATED by protocol/codegen/generate.ts — DO NOT EDIT BY HAND. */
#ifndef AGENTBUS_PROTOCOL_H
#define AGENTBUS_PROTOCOL_H

#define AGENTBUS_VERSION 1

/* Wire frame: [u32 length BE][u8 type][u32 session_id BE][json payload]
   length counts everything after the length field. */

#define AGENTBUS_MSG_HELLO 1  /* down: server greeting + protocol version + capabilities */
#define AGENTBUS_MSG_SESSION_LIST 2  /* down: full list of sessions for the board */
#define AGENTBUS_MSG_SESSION_STATE 3  /* down: one session's state + capability descriptor */
#define AGENTBUS_MSG_OUTPUT_CHUNK 4  /* down: streamed agent output for a session */
#define AGENTBUS_MSG_APPROVAL_REQUEST 5  /* down: a pending tool call needs approve/deny */
#define AGENTBUS_MSG_TRANSCRIPT_PARTIAL 6  /* down: streaming STT partial/final transcript */
#define AGENTBUS_MSG_MACROPAD_LAYOUT 7  /* down: host-pushed bottom-screen layout keyed to state */
#define AGENTBUS_MSG_ERROR 8  /* down: an error scoped to a session or the connection */
#define AGENTBUS_MSG_REPLAY_BEGIN 9  /* down: start of a reconnect replay burst */
#define AGENTBUS_MSG_REPLAY_END 10  /* down: end of a reconnect replay burst (carries truncation marker) */
#define AGENTBUS_MSG_ATTACH 64  /* up: device handshake; carries auth token + optional reconnect cursor */
#define AGENTBUS_MSG_FOCUS_SESSION 65  /* up: device focuses a tile */
#define AGENTBUS_MSG_PROMPT_TEXT 66  /* up: typed prompt for the focused session */
#define AGENTBUS_MSG_INPUT_EVENT 67  /* up: generic button/touch event */
#define AGENTBUS_MSG_APPROVAL_RESPONSE 68  /* up: allow/deny for a pending approval */
#define AGENTBUS_MSG_AUDIO_CHUNK 69  /* up: PCM audio during push-to-talk */
#define AGENTBUS_MSG_MACRO_INTENT 70  /* up: a macro firing as a protocol-level intent */
#define AGENTBUS_MSG_INTERRUPT 71  /* up: interrupt the focused session */

/* Secure-transport + discovery constants (U23). */
#define AGENTBUS_KEY_BYTES 32  /* XChaCha20-Poly1305 pre-shared key length */
#define AGENTBUS_NONCE_BYTES 24  /* per-frame random nonce (192-bit, random-safe) */
#define AGENTBUS_MAC_BYTES 16  /* Poly1305 authentication tag */
#define AGENTBUS_MAX_RECORD_BYTES 16380  /* max sealed record (nonce|ct|mac); == client RXBUF minus the 4-byte outer length prefix. Both ends enforce this before buffering. */
#define AGENTBUS_EPOCH_BYTES 8  /* per-connection anti-replay epoch, host-minted */
#define AGENTBUS_SEQ_BYTES 8  /* per-direction monotonic counter (in AAD, not on wire) */
#define AGENTBUS_DIR_DOWN 0  /* AAD direction byte: host -> device */
#define AGENTBUS_DIR_UP 1  /* AAD direction byte: device -> host */
#define AGENTBUS_CHALLENGE_BYTES 8  /* discovery probe random challenge */
#define AGENTBUS_DISCOVERY_PROBE 1  /* discovery datagram TYPE: device -> host probe */
#define AGENTBUS_DISCOVERY_REPLY 2  /* discovery datagram TYPE: host -> device reply */
#define AGENTBUS_DEFAULT_TCP_PORT 4791  /* AgentBus TCP port (host listens) */
#define AGENTBUS_DEFAULT_DISCOVERY_PORT 41337  /* UDP discovery port (host responder) */
#define AGENTBUS_AAD_MSG_CONTEXT "ag3nt-msg-v1"  /* AAD domain tag for TCP frames */
#define AGENTBUS_AAD_DSC_CONTEXT "ag3nt-dsc-v1"  /* AAD domain tag for discovery datagrams */
#define AGENTBUS_DISCOVERY_MAGIC "ag3n"  /* discovery datagram magic prefix */

#endif /* AGENTBUS_PROTOCOL_H */
