/* GENERATED by protocol/codegen/generate.ts — DO NOT EDIT BY HAND. */
#ifndef AGENTBUS_PROTOCOL_H
#define AGENTBUS_PROTOCOL_H

#define AGENTBUS_VERSION 1

/* Wire frame: [u32 length BE][u8 type][u32 session_id BE][json payload]
   length counts everything after the length field. */

#define AGENTBUS_MSG_HELLO 1  /* down: server greeting + protocol version + capabilities */
#define AGENTBUS_MSG_SESSION_LIST 2  /* down: full list of sessions for the board */
#define AGENTBUS_MSG_SESSION_STATE 3  /* down: one session's state + capability descriptor */
#define AGENTBUS_MSG_OUTPUT_CHUNK 4  /* down: streamed agent output for a session */
#define AGENTBUS_MSG_APPROVAL_REQUEST 5  /* down: a pending tool call needs approve/deny */
#define AGENTBUS_MSG_TRANSCRIPT_PARTIAL 6  /* down: streaming STT partial/final transcript */
#define AGENTBUS_MSG_MACROPAD_LAYOUT 7  /* down: host-pushed bottom-screen layout keyed to state */
#define AGENTBUS_MSG_ERROR 8  /* down: an error scoped to a session or the connection */
#define AGENTBUS_MSG_REPLAY_BEGIN 9  /* down: start of a reconnect replay burst */
#define AGENTBUS_MSG_REPLAY_END 10  /* down: end of a reconnect replay burst (carries truncation marker) */
#define AGENTBUS_MSG_ATTACH 64  /* up: device handshake; carries auth token + optional reconnect cursor */
#define AGENTBUS_MSG_FOCUS_SESSION 65  /* up: device focuses a tile */
#define AGENTBUS_MSG_PROMPT_TEXT 66  /* up: typed prompt for the focused session */
#define AGENTBUS_MSG_INPUT_EVENT 67  /* up: generic button/touch event */
#define AGENTBUS_MSG_APPROVAL_RESPONSE 68  /* up: allow/deny for a pending approval */
#define AGENTBUS_MSG_AUDIO_CHUNK 69  /* up: PCM audio during push-to-talk */
#define AGENTBUS_MSG_MACRO_INTENT 70  /* up: a macro firing as a protocol-level intent */
#define AGENTBUS_MSG_INTERRUPT 71  /* up: interrupt the focused session */

#endif /* AGENTBUS_PROTOCOL_H */
